vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        vehicle_images:
            uri_prefix: /images/vehicles
            upload_destination: '%kernel.project_dir%/public/images/vehicles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           #uri_prefix: /images/products
           #upload_destination: '%kernel.project_dir%/public/images/products'
           #namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
